// <auto-generated />
namespace Example.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _delete_user_username : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_delete_user_username));
        
        string IMigrationMetadata.Id
        {
            get { return "201704240929018__delete_user_username"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
