// <auto-generated />
namespace Example.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _update_col_id_longnullable_to_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_update_col_id_longnullable_to_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201704260809218__update_col_id_long[nullable]_to_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
